# ==================================================
# Application Configuration
# ==================================================

application.name=QuantityMeasurement

# ==================================================
# Repository Configuration
# ==================================================

repository.type=jdbc

# ==================================================
# Database Configuration
# ==================================================

database.driver=org.h2.Driver

database.url=jdbc:h2:mem:quantity_measurement;DB_CLOSE_DELAY=-1

database.username=sa

database.password=

# ==================================================
# Schema Configuration
# ==================================================

database.schema=db/schema.sql

# ==================================================
# Logging
# ==================================================

logging.enabled=true

logging.level=INFO